OrdererOrgs:
        - Name: Orderer
          Domain: example.com
          EnableNodeOUs: false
          Specs:
                  - Hostname: orderer
                    SANS:
                            - localhost

